"""empty message

Revision ID: 63225e7ba51b
Revises: 
Create Date: 2018-02-03 19:20:42.883059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63225e7ba51b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmation_token', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmation_token')
    # ### end Alembic commands ###
