"""empty message

Revision ID: 696ba01eef22
Revises: 63225e7ba51b
Create Date: 2018-02-03 23:12:27.796387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696ba01eef22'
down_revision = '63225e7ba51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
